### ISSUE TITLE
Fails to generate sprite with SVGs from Illustrator

### ISSUE THREAD

**Issue by WillsB3** [drdk/grunt-dr-svg-sprites#26]
Am I doing something wrong here?

Things work (kind of..) if I export as SVG from sketch (apart from paths with boolean operations seem to cause problems, but that's perhaps a different issue), however whenever I try to export from illustrator the SVG is just blank. If i look at the source of the SVG there several occurrences of "NaN".

Here's the export settings I'm using:

![screen shot 2014-08-08 at 09 35 47](https://cloud.githubusercontent.com/assets/868834/3854413/0392107e-1ed7-11e4-9ee8-0b86d8c3589a.png)

Here's my gruntfile config (using grunt-load-config YAML syntax):

``` yaml
options:
  prefix: 'sprite'

sprite:
  options:
    spriteElementPath: '<%= src.assets %>/icons'
    spritePath: '<%= tmp.assets %>/icons/sprite.svg'
    cssPath: '<%= tmp.css %>/sprite.css'
```

The generated CSS looks like this:

``` css
.sprite-test {
    width: NaNpx;
    height: NaNpx;
    background-position: 0 0;
}

.sprite-test {
    background-size: NaNpx NaNpx;
    background-repeat: no-repeat;
    background-image: url("../assets/icons/sprite.png");
}

.svg .sprite-test {
    background-image: url("../assets/icons/sprite.svg");
}
```

If I open the very same SVG which Illustrator saved and then re-export it with sketch, it works.

Here's some test SVGs:
- Working, exported via Sketch: http://cl.ly/233d2p0u1h3Z
- Not working, exported via Illustrator: http://cl.ly/3f0u1e2f390C
