### ISSUE TITLE
Custom Css background-image URL in output

### ISSUE THREAD

**Issue by dutchwebworks** [drdk/grunt-dr-svg-sprites#47]
I'm trying to change the final Css `background-image` URL path in the output to a custom **root relative** path.

Currently it's **relative** to the Css file:

````css
.no-svg .sprite-main-image-01, .no-svg .sprite-main-image-02 {
	background-image: url("../img/sprites/main-sprite.png");
}

.svg .sprite-main-image-01, .svg .sprite-main-image-02 {
	background-image: url("../img/sprites/main-sprite.svg");
}
````
But I want to customize it to a **root relative path** (or maybe even a hardcoded CDN like URL):

````css
.no-svg .sprite-main-image-01, .no-svg .sprite-main-image-02 {
	background-image: url("/themes/main/img/sprites/main-sprite.png");
}

.svg .sprite-main-image-01, .svg .sprite-main-image-02 {
	background-image: url("/themes/main/img/sprites/main-sprite.svg");
}
````
Because our backend code minifies, bundles and then **serves the Css file from a different URL** so the relative path does not resolve.

I've tried fiddling with a custom Handlebar template:

````handlebars
background-image: url("{{url ../svgPath ../cssPath}}");
````

But I can't seem to change the `url` helper nor the two arguments. When changing the two argument somehow generates a very long unwanted local filesystem path.
