### ISSUE TITLE
Invalid CSS file if sprite path doesn't have any svg file

### ISSUE THREAD

**Issue by pomek** [drdk/grunt-dr-svg-sprites#50]
Hi,

I will create a new project. I've prepared scaffolding, which contains your plugin. 

I would like to test it, but if my directory with svg files doesn't have any svg files, plugin will generate invalid stylesheet. 

```css
 {
	background-size: -Infinitypx -Infinitypx;
	background-repeat: no-repeat;
	background-image: url("svg-sprite.png");
}

.svg  {
	background-image: url("svg-sprite.svg");
}
```

First block doesn't have any identifier. `background-size` has invalid value (Infinity). Because of that Sass task will fail. 

Everything works fine when directory with svg files will contain at least one svg file.

I can prepare some fix. Are you interested in?
